version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imctestfiles
    image: yknam/imctestfiles
    volumes:
      - ./src:/app/src
    ports:
      - "4009:80"
